#pragma once
#include <algorithm>
#include <cstdint>
#include <fstream>
#include <memory>
#include <random>
#include <string>
using namespace std;

constexpr uint32_t MID_PRICE = 10000;
constexpr int SEED_ORDERS = 10000;
constexpr int SEED_DEPTH = 50;
constexpr long TRADING_ORDERS = 5'000'000;
constexpr uint32_t RNG_SEED = 42;
constexpr int PRICE_BAND = 500;
constexpr size_t WRITE_BUF_BYTES = 4 * 1024 * 1024;

// Lightweight market state used only to keep generated flow coherent.
// The real LOB built by the matching engine is the source of truth at run time.
struct SimState {
    int32_t refPrice;
    int32_t simBestBid;
    int32_t simBestAsk;
};

static void seed_book(ofstream &out, mt19937 &rng) {
    uniform_int_distribution<int> sizeDist(1, 100);

    // Round-robin across SEED_DEPTH levels per side so every price tick
    // near the touch has resting liquidity from the first trading order.
    for (int i = 0; i < SEED_ORDERS; i++) {
        const bool buy = (i % 2 == 0);
        const int offset = (i / 2) % SEED_DEPTH + 1;
        const uint32_t price = buy ? MID_PRICE - offset : MID_PRICE + offset;
        const int shares = sizeDist(rng);
        out << (buy ? 'B' : 'S') << ' ' << price << ' ' << shares << '\n';
    }
}

static void generate_trading_flow(ofstream &out, mt19937 &rng, SimState &sim) {
    bernoulli_distribution sideDist(0.5);
    bernoulli_distribution aggressiveDist(0.30);
    bernoulli_distribution driftDist(0.005);
    bernoulli_distribution largeAggDist(0.20);
    uniform_int_distribution<int> driftStep(-1, 1);
    uniform_int_distribution<int> aggOffset(0, 3);
    uniform_int_distribution<int> passiveOffset(1, 15);
    uniform_int_distribution<int> sizeDist(1, 100);
    uniform_int_distribution<int> largeSizeDist(10, 200);

    const int32_t lowerBand = static_cast<int32_t>(MID_PRICE) - PRICE_BAND;
    const int32_t upperBand = static_cast<int32_t>(MID_PRICE) + PRICE_BAND;

    for (long i = 0; i < TRADING_ORDERS; i++) {
        if (driftDist(rng)) {
            sim.refPrice = std::clamp(sim.refPrice + driftStep(rng), lowerBand, upperBand);
        }

        const bool buy = sideDist(rng);
        const bool aggressive = aggressiveDist(rng);

        int32_t price;
        if (buy) {
            price = aggressive
                ? sim.refPrice + aggOffset(rng)
                : sim.refPrice - passiveOffset(rng);
        } else {
            price = aggressive
                ? sim.refPrice - aggOffset(rng)
                : sim.refPrice + passiveOffset(rng);
        }

        price = std::clamp(price, lowerBand, upperBand);
        if (price < 1) price = 1;

        if (aggressive) {
            if (buy && price >= sim.simBestAsk) {
                sim.simBestAsk = std::clamp(price + 1, lowerBand, upperBand);
            } else if (!buy && price <= sim.simBestBid) {
                sim.simBestBid = std::clamp(price - 1, 1, upperBand);
            }
        }

        const int shares = (aggressive && largeAggDist(rng))
            ? largeSizeDist(rng)
            : sizeDist(rng);

        out << (buy ? 'B' : 'S') << ' ' << price << ' ' << shares << '\n';
    }
}

void create_random_input(string filename) {
    ofstream out;
    auto buf = std::make_unique<char[]>(WRITE_BUF_BYTES);
    out.rdbuf()->pubsetbuf(buf.get(), WRITE_BUF_BYTES);
    out.open(filename);

    out << "# Generated by cpp-lob -r\n";
    out << "# mid=" << MID_PRICE
        << " seed_orders=" << SEED_ORDERS
        << " trading_orders=" << TRADING_ORDERS
        << " rng_seed=" << RNG_SEED << '\n';

    mt19937 rng(RNG_SEED);

    seed_book(out, rng);

    SimState sim{
        static_cast<int32_t>(MID_PRICE),
        static_cast<int32_t>(MID_PRICE) - 1,
        static_cast<int32_t>(MID_PRICE) + 1,
    };
    generate_trading_flow(out, rng, sim);

    out.close();
}
